language: rust

rust:
    - stable
    - beta
    - nightly

os:
    - linux
    - osx
    - windows

arch:
    - amd64
    - arm64

matrix:
    allow_failures:
        - rust: nightly

notifications:
    email:
        on_success: never
        on_failure: never

script:
    - cargo test
    - cargo doc --no-deps
