[package]
name = "data-test"
version = "0.1.0"
authors = ["Jesús Hernández <jesushdez@protonmail.com>"]
edition = "2018"
license = "Unlicense"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
